### ISSUE TITLE
Add support for Ghost In The Shell First Assault.

### ISSUE THREAD

**Issue by n1-d** [niftools/nifskope#87] opened 2015-10-14 16:56 UTC
It does not work at all with this new version of GameBryo as it only shows the bone of the character like  shown.

http://i.imgur.com/VXeMMPl.png

**Comment by hexabits** [comment] 2015-10-15 11:36
@no1dead @ttl269 @neomonkeus 

This is better reported in the NifTools forums.  Tickets for supporting an entire game/version aren't really an intended use of the Issues, as there are too many variables or it's too general.  You don't say if nif.xml needs updating or it's solely a rendering issue.  You don't say what the NIF version actually is.   If it's around 20.5.x - 20.6.x or later, the issue is definitely known because NifSkope cannot render NiMesh/NiDataStream blocks.  If it's 30.x.x it may not even be decoded. 

Also, when you're reporting a particular game you should also be including a varied selection of NIF / texture files.

Anyway, if you're getting errors on load, then nif.xml is not updated and you first need to post here:

http://niftools.sourceforge.net/forum/viewforum.php?f=10

Making sure to provide some files.  First make sure to look at some of the topics and see if there is already a topic for that NIF version.

I'll leave this open for a few days but then I'll be closing it.  If you provide more information then I will be able to determine what the specific issue actually is and create a ticket myself.  If the game uses the NiMesh/NiDataStream format, then I'm already aware and I will be making a ticket eventually.

**Comment by neomonkeus** [comment] 2015-10-15 12:59
Think @jonwd7 has covered the main points. We need to see what level of support is currently there and the establish what components would be affected, ie format, libraries, tools, plug ins etc.

Posting in the forum with samples is probably the best option.

**Comment by n1-d** [comment] 2015-10-15 19:05
Sorry about that it was on my phone and there was not much info I could give.

**Comment by n1-d** [comment] 2015-10-15 19:17
So I did update the nif.xml to Gamebryo File Format, Version 30.2.0.3 and the picture I posted is what happens when I did it. I'm not really sure how to update nif.xml properly so I did what I could.

Here's a link to a models nif files and textures
http://files.catbox.moe/1113f4.zip

EDIT:

I'd say it was a rendering issue, but using the 3DSMax Importer for .nif also does the same thing so I do believe that its not being decoded.

**Comment by hexabits** [comment] 2015-10-15 20:44
> So I did update the nif.xml to Gamebryo File Format, Version 30.2.0.3 and the picture I posted is what happens when I did it.

Could you clarify?   I know there was some work done on decoding 30.1.0.3, but not 30.2.0.3.  Did you get a nif.xml from somewhere where support was added for 30.2.0.3?   If you manually edited something, like changing 30.1.0.3 to 30.2.0.3 in the top of the XML file, then you were doing it wrong.

Anyway, opening the file you provided with the latest nif.xml shows that 30.2.0.3 is not even supported, so the first action is to actually decode it and add the data definitions to nif.xml. 

Someone else has [posted about 30.2.0.3](http://niftools.sourceforge.net/forum/viewtopic.php?f=10&t=5980) and from what I can tell, the format does use NiMesh/NiDataStream, so yes,  NifSkope cannot display it.  

So, if you want to ask for 30.2.0.3 support in nif.xml,  I'd suggest posting in the Decoding forum, or adding to the existing topic for 30.2.0.3 I linked above.  This will at least allow you to open the files without error and edit some of their properties.

Actually _viewing_ the models in NifSkope might never happen however.  It relies upon decoding and understanding NiMesh/NiDataStream blocks and whether these blocks vary between versions.   The issue is that nif.xml is not set up to handle these variations because right now nif.xml treats the important part of NiDataStream as one giant blob of data, since we know nothing about it.  Someone at some point did attempt to decode it, and I [talk a bit about that here](http://niftools.sourceforge.net/forum/viewtopic.php?f=10&t=2757#p31705). 

There is also this topic about it: http://forum.xentax.com/viewtopic.php?f=16&t=8043

Anyway, I will leave this open for more comments, but as I said before,  I will instead create a more appropriate ticket about NiMesh/NiDataStream, which is the actual issue brought up here.  Though doing so would be kind of pointless right now because the work is actually in decoding it and updating nif.xml, so maybe instead I will create the ticket over at niftools/nifxml.

**Comment by hexabits** [comment] 2015-10-23 16:43
Well, it's been a week, so I think anything that was said already was.  I will create a ticket for NiMesh/NiDataStream at a later date, after assessing where the work actually needs to be done.  I am guessing nif.xml actually needs to decode it first.  So the ticket would be over at niftools/nifxml.

**Closed as completed by hexabits** 2015-10-23 16:43 UTC

**Comment by hexabits** [comment] 2017-10-07 01:08
Just for the record, 30.2.0.3 loads with nifxml 0.9 (https://github.com/niftools/nifxml/pull/65) and 2.0dev7 (https://github.com/niftools/nifskope/pull/115) including this game.
