### ISSUE TITLE
Nifscope: there were errors during shader compilation

### ISSUE THREAD

**Issue by erikabear1990** [niftools/nifskope#99] opened 2016-09-06 04:49 UTC
how do I install nifscope? i download the file and extract the file and when i run the exe a popup says: there were errors during shader compilation

ob_normalmap_vcol_e.prog:

The fragment shader uses varying D, but previous shader does not write to it.
The fragment shader uses varying A, but previous shader does not write to it.

ob_parallax+glowmap.prog:

The fragment shader uses varying HalfVector, but previous shader does not write to it.

ob_parallax.prog:

The fragment shader uses varying HalfVector, but previous shader does not write to it.

ob_parallax_vcol_ad.prog:

The fragment shader uses varying HalfVector, but previous shader does not write to it.﻿

**Comment by hexabits** [comment] 2016-09-12 06:41
@erikabear1990  Those shaders are irrelevant/obsolete and you can just remove the files if you are sick of the error.  Note the error doesn't say "This entire program is unusable because of shader compilation errors"... it's just informing you that some of them didn't compile, i.e. a nuisance. 

Secondly, this specific issue is exclusive to certain development builds and thus it's not appropriate to be posting it here.  I removed this specific issue in later builds, which you can find here: http://afkmods.iguanadons.net/index.php?/topic/4136-nifskope-20-dev/?p=162363

Lastly, this is a near-complete duplicate of #97 where I said the same thing.

**Closed as completed by hexabits** 2016-09-12 06:41 UTC
Labels: S:duplicate
