### ISSUE TITLE
Pls add Epic Mickey 2 support

### ISSUE THREAD

**Issue by Techttv** [niftools/nifskope#215] opened 2022-06-06 11:24 UTC
Hi there, could u add the support to EM2 pls? There's an entire community which is trying to bring back to life his fav game and we need ur help to do that.  Thx for everything I hope you'll add it.

**Comment by neomonkeus** [comment] 2022-06-07 10:11
Currently we have no active NifSkope Dev
Also duplicate of #172

**Closed as completed by neomonkeus** 2022-06-07 10:11 UTC
Labels: S:duplicate
