### ISSUE TITLE
Cleanup unused strings in resulting Nif's

### ISSUE THREAD

**Issue by L0FKA** [niftools/nifskope#20] opened 2013-12-07 20:58 UTC
Nifskope doesn't clear unused strings after deletion its instance\place where it was used and its causing some problems to me, I can't reorganise NIf as I want, also I need to include small program to Nif that creates reverse animation for direct animation :) (p.s, I having math)

**Comment by hexabits** [comment] 2014-01-31 15:49
Duplicate of #18

**Closed as completed by hexabits** 2014-01-31 15:49 UTC
Labels: T:feature
